### PR TITLE
narrow down logging from ipython

### PR DESCRIPTION
**Pull request by fgregg**
this PR narrows down what gets bubbled up from ipython to just the traceback. Only reorganizes the code a bit for clarity.

### CODE REVIEW

**Comment by piccolbo** [comment]
Please if there is no associated ticket spend two more sentences to explain what and why. What messages did you drop and why is it better? I am all for less red tape, but 0 doesn't leave a record of why things were done. Also I liked the simplicity of just saying, if ipython produces it, you are going to see it with -v. Now some stuff is left out, more complicated. I am sure there was a reason and we can always add a -vv and a -vvv options at later time where you get to see more and more. Let's just record what the reason was. Thanks

**Comment by fgregg** [comment]
Sure!

Before:
```bash
pweave -v FIR_design_verb.texw
status
status
Processing chunk 1 named None from line 93
INFO:ipykernel.inprocess.ipkernel:Exception in execute request:
------------------------------------------------------------------
RuntimeError                     Traceback (most recent call last)
<ipython-input-1-6dc102a41cde> in <module>()
      1 from pylab import *
      2 import scipy.signal as signal
----> 3 raise
      4 
      5 #Plot frequency and phase response

RuntimeError: No active exception to reraise
Processing chunk 2 named None from line 117
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 801, "Aborting:">
INFO:ipykernel.inprocess.ipkernel:Aborting:
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 802, "%s">
INFO:ipykernel.inprocess.ipkernel:{'header': {'msg_id': '8b59d8bd-0690aca97db1ded3aa66bdd0', 'msg_type': 'execute_request', 'username': 'fgregg', 'session': '2f2ae8f8-69f5ddeea956c236ba97dd9a', 'date': datetime.datetime(2018, 12, 15, 2, 58, 52, 160171, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': '8b59d8bd-0690aca97db1ded3aa66bdd0', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': 'matplotlib.rcParams.update({"figure.figsize" : (6, 4)})\nmatplotlib.rcParams.update({"figure.dpi" : 200})', 'silent': False, 'store_history': False, 'user_expressions': {}, 'allow_stdin': False}, 'buffers': []}
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 801, "Aborting:">
INFO:ipykernel.inprocess.ipkernel:Aborting:
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 802, "%s">
INFO:ipykernel.inprocess.ipkernel:{'header': {'msg_id': 'be8562cb-19f735e0ff6b7afdd06e4846', 'msg_type': 'execute_request', 'username': 'fgregg', 'session': '2f2ae8f8-69f5ddeea956c236ba97dd9a', 'date': datetime.datetime(2018, 12, 15, 2, 58, 52, 163321, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': 'be8562cb-19f735e0ff6b7afdd06e4846', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': 'n = 61\na = signal.firwin(n, cutoff = 0.3, window = "hamming")\n#Frequency and phase response\nmfreqz(a)\n#Impulse and step response\np = figure(2)\nimpz(a)', 'silent': False, 'store_history': False, 'user_expressions': {}, 'allow_stdin': False}, 'buffers': []}
Processing chunk 3 named None from line 127
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 801, "Aborting:">
INFO:ipykernel.inprocess.ipkernel:Aborting:
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 802, "%s">
INFO:ipykernel.inprocess.ipkernel:{'header': {'msg_id': '7692bdd9-3ca274eed1d5267b8ec5f470', 'msg_type': 'execute_request', 'username': 'fgregg', 'session': '2f2ae8f8-69f5ddeea956c236ba97dd9a', 'date': datetime.datetime(2018, 12, 15, 2, 58, 52, 166637, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': '7692bdd9-3ca274eed1d5267b8ec5f470', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': 'matplotlib.rcParams.update({"figure.figsize" : (6, 4)})\nmatplotlib.rcParams.update({"figure.dpi" : 200})', 'silent': False, 'store_history': False, 'user_expressions': {}, 'allow_stdin': False}, 'buffers': []}
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 801, "Aborting:">
INFO:ipykernel.inprocess.ipkernel:Aborting:
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 802, "%s">
INFO:ipykernel.inprocess.ipkernel:{'header': {'msg_id': '730a16c0-c175e0edda7b0e21d632a084', 'msg_type': 'execute_request', 'username': 'fgregg', 'session': '2f2ae8f8-69f5ddeea956c236ba97dd9a', 'date': datetime.datetime(2018, 12, 15, 2, 58, 52, 169712, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': '730a16c0-c175e0edda7b0e21d632a084', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': 'n = 101\na = signal.firwin(n, cutoff = 0.3, window = "hanning", pass_zero=False)\nmfreqz(a)', 'silent': False, 'store_history': False, 'user_expressions': {}, 'allow_stdin': False}, 'buffers': []}
Processing chunk 4 named None from line 138
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 801, "Aborting:">
INFO:ipykernel.inprocess.ipkernel:Aborting:
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 802, "%s">
INFO:ipykernel.inprocess.ipkernel:{'header': {'msg_id': 'e42c5c20-deb58b4ad044ac45b95713cc', 'msg_type': 'execute_request', 'username': 'fgregg', 'session': '2f2ae8f8-69f5ddeea956c236ba97dd9a', 'date': datetime.datetime(2018, 12, 15, 2, 58, 52, 177108, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': 'e42c5c20-deb58b4ad044ac45b95713cc', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': 'matplotlib.rcParams.update({"figure.figsize" : (6, 4)})\nmatplotlib.rcParams.update({"figure.dpi" : 200})', 'silent': False, 'store_history': False, 'user_expressions': {}, 'allow_stdin': False}, 'buffers': []}
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 801, "Aborting:">
INFO:ipykernel.inprocess.ipkernel:Aborting:
<LogRecord: ipykernel.inprocess.ipkernel, 20, /Users/fgregg/work/Pweave/.env/lib/python3.7/site-packages/ipykernel/kernelbase.py, 802, "%s">
INFO:ipykernel.inprocess.ipkernel:{'header': {'msg_id': '3db222ef-383881d925247edc76c3d992', 'msg_type': 'execute_request', 'username': 'fgregg', 'session': '2f2ae8f8-69f5ddeea956c236ba97dd9a', 'date': datetime.datetime(2018, 12, 15, 2, 58, 52, 180029, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': '3db222ef-383881d925247edc76c3d992', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': "n = 1001\na = signal.firwin(n, cutoff = [0.2, 0.5], window = 'blackmanharris', pass_zero = False)\nmfreqz(a)", 'silent': False, 'store_history': False, 'user_expressions': {}, 'allow_stdin': False}, 'buffers': []}
Weaved FIR_design_verb.texw to FIR_design_verb.tex
```

After:

```bash
pweave -v FIR_design_verb.texw
status
status
Processing chunk 1 named None from line 93
INFO:ipykernel.inprocess.ipkernel:Exception in execute request:
------------------------------------------------------------------
RuntimeError                     Traceback (most recent call last)
<ipython-input-1-6dc102a41cde> in <module>()
      1 from pylab import *
      2 import scipy.signal as signal
----> 3 raise
      4 
      5 #Plot frequency and phase response

RuntimeError: No active exception to reraise
Processing chunk 2 named None from line 117
Processing chunk 3 named None from line 127
Processing chunk 4 named None from line 138
Weaved FIR_design_verb.texw to FIR_design_verb.tex
```

**Comment by piccolbo** [comment]
OK those were not quite sentences but the examples will do. Checks are failing for unrelated reasons I suspect. Should be solved now in master. When master checks fine can you merge it into this? Thanks

**Comment by piccolbo** [comment]
As of  Commit 62a740e  tests clear on master.

**Comment by fgregg** [comment]
It seems you don't like my communication style or my development practices. Let's part ways. Good luck.

**Comment by piccolbo** [comment]
Sorry to hear that. Thanks for your contributions thus far.

**Pull request closed without merging**
