### PR TITLE
Verbose logging

### PR DESCRIPTION
**Pull request by fgregg**
Hi @piccolbo, let me know if you'd like some version of this in your fork. There are other things I'd like to see done with Pweave, and it would be good to find collaborators.

### CODE REVIEW

**Comment by piccolbo** [comment]
Will take a look tomorrow. Thanks.

**Comment by piccolbo** [comment]
There's a failed test on py 3.5 if you could take a look. Or we drop 3.5 support and move on.

**Comment by piccolbo** [comment]
By the way I normally use black as a formatter because it outputs code that only depend on the parse tree, not any quirks in how it was typed, and puts an end to formatting disputes. It's pep8-compliant, not how I would format things, but better than formatting wars. I see from some reformatting you did you may use something similar. It'd be best to align to keep the diffs small.

**Comment by fgregg** [comment]
Makes sense to me to get tests passing before we start bringing in feature PRs. see #2. 

I'm also happy to code formatting scheme you like. After nosetests are passing, would you want to make the existing code base black-compliant, and then add a black linter to the CI?

**Comment by piccolbo** [comment]
Sounds like a plan. Even better for me,  pre-commit action to format everything, but I need to research it. Linting means another class of failures you have to deal with -- for a good reason but more work. A formatter just does the work for you. I like that better. We are digressing a bit too much on this PR I will open a few issues to focus the discussion.

**Comment by piccolbo** [comment]
I will do the formatting. You seem to know what you are doing on the CI.
black --check to run a check without changes, --diff to get a diff of what
would have to change.

**Comment by piccolbo** [comment]
Can you merge master again? Then this should pass. Or I can do it.

**Comment by fgregg** [comment]
I rebased and squashed. Test passing now. @piccolbo

**Comment by piccolbo** [comment]
I am against either, but that's a longer story (https://git-scm.com/book/en/v2/Git-Branching-Rebasing , section "perils of rebasing") . Will do for now.

**Pull request merged**
